# Generated by Django 2.2.3 on 2023-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('password_again', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginModels',
        ),
        migrations.RenameField(
            model_name='loginmodels',
            old_name='passwrod',
            new_name='password',
        ),
    ]
